# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy to Hostinger (static Next.js)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install deps
        run: npm ci

      - name: Build (Next.js)
        run: npm run build

      - name: Upload via FTP
        if: ${{ env.SFTP != 'true' }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./out
          server-dir: /public_html
          dangerous-clean-slate: true

      - name: Upload via SFTP
        if: ${{ env.SFTP == 'true' }}
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_HOST }}
          port: ${{ secrets.FTP_PORT }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './out/*'
          remote_path: '/public_html'
          args: '-o StrictHostKeyChecking=no'
